# Site settings
title: Abigail Chaver
email: abigailchaver@berkeley.edu
url: http://abbeychaver.github.io
description: "Data Science at UC Berkeley"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 272F65; #indigo
  secondary: 56CCF2; #bright blue
  secondary-dark: 8E91BD; #233140 #A2122F
  light: E8E9F2;

# Footer settings
footer:
  copyright: Abigail Chaver


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/abbeychaver
  #- title: facebook
    #url:
  #- title: stack-overflow
    #url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
    #url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/abbeychaver
  - title: linkedin
    url: https://www.linkedin.com/pub/abbey-chaver/38/3a7/8a5


# Credits content
#credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: redcarpet

